### ISSUE TITLE
Moto G4 Play will see Minecraft white screen then crash

### ISSUE THREAD

**Issue by craftablescience** [zhuowei/MCPELauncher#1466] opened 2017-11-26 18:02 UTC
My Moto G4 Play can run BlockLauncher with no mods or texture packs, but when a mod is applied it will only show "Minecraft" with a white background then crash.

**Comment by zhuowei** [comment] 2017-11-27 04:10
which mod? Do you have a link to the mod?

**Comment by blewis14** [comment] 2017-11-27 11:49
Yes, it is the latest version of DesnoGuns

**Comment by zhuowei** [comment] 2017-11-29 07:11
@blewis14 I can't reproduce it on my device (Huawei Nexus 6P). Can you take a bug report after the crash, upload it to Google Drive, and post the link here? https://www.youtube.com/watch?v=YxQ3NTloD2c

**Comment by blewis14** [comment] 2017-12-01 13:32
Sorry about the delay, I'll get around to it on the weekend.

**Comment by blewis14** [comment] 2017-12-02 19:26
Here you go:
[bugreport-2017-12-02-14-16-58.zip](https://drive.google.com/file/d/1Ec2fM8XOeAhV6wA34y_ecY8HNndBqrQu/view?usp=sharing)

**Comment by blewis14** [comment] 2017-12-18 16:17
@zhuowei If you are not working on this issue I can close it

**Closed** 2019-03-20 22:07 UTC
