### ISSUE TITLE
Crashed

### ISSUE THREAD

**Issue by vtlev** [zhuowei/MCPELauncher#1201] opened 2016-06-29 10:26 UTC
Error message:
Unfortunately block launcher pro has stopped.

Minecraft version 0.15.1
Devices: 
   Nexus 6 , Android 6.0.1
   Kindle fire 7 - brand new from Amazon last week

The free version worked fine in an older galaxy s4 on Android 4.2.2 so I thought I'd try the pro version on the new Kindle, which didn't work and so I tried it on the Nexus 6 and that failed  as well.

**Comment by vtlev** [comment] 2016-06-29 10:29
block launcher pro 1.12.8

**Comment by zedman2000** [comment] 2016-06-29 13:17
1.12.28 is not compatible with 0.15.x.  Either revert to an earlier version of Minecraft or wait until BL is updated.  Sorry.

@vtlev thank you for posting a NICE message.  Most people are being nasty...which to me is not suitable for posting issues.

**Comment by zedman2000** [comment] 2016-06-29 13:19
Since the issue is with version incompatibility, can you please close this issue so that the author does not have to sort this out later?  Thanks!

**Comment by vtlev** [comment] 2016-06-29 16:15
Hi Daniel,

Thanks for your quick response.  Do you have instruction for reverting to an older version of Minecraft PE?  I didn't know that was possible.

I am looking to teach my son JavaScript and he likes Minecraft, so I am hopeful to get a combo that would work.

I think BL is a very good Minecraft wrapper program.  Must be really frustrating dealing with all the versions of Minecraft from a development standpoint.

I will close out the issue.

Vinh

On Jun 29, 2016 9:18 AM, Daniel Rozwood <notifications@github.com> wrote:

1.12.28 is not compatible with 0.15.x. Either revert to an earlier version of Minecraft or wait until BL is updated. Sorry.

@vtlev<https://github.com/vtlev> thank you for posting a NICE message. Most people are being nasty...which to me is not suitable for posting issues.

**Closed** 2016-06-29 16:17 UTC

**Comment by zedman2000** [comment] 2016-06-29 16:32
@vtlev If you have something like TitaniumBackup that would allow you.  The trick was you needed to have a copy of it already backed up.  Since the release of 0.15 is official, I think you cannot revert using the Google Play Store.  There might also be some ways to side-load using APK files floating around on the internet, however I would not recommend that as you do not know if those APK files have been tampered with.  You might also have a friend that still has an older version.  If so, you could also use something like APK EXTRACTOR from the Google Play Store.  Then, side-load the image back to your device.  MrARM has a ToolBox beta out right now, you can look him up on Twitter and try his launcher as a temporary thing.  His launcher supports some scripting as well as texture pack loading.  I have not tried is so YMMV.  I can only say that Zhuowei has been working hard and everyone seems to be forgetting the steps that he needs to take to get this to work.  Also, since Mojang released 3-4 versions in a row, that has impacted Zhuowei's work and forced him to start over a few times.  It takes time and patience is needed for something that essentially hooks into the game a REALLY low code level.

Since all of those methods are a bit shady and I would not really recommend them, the best suggestion I have is be patient and wait.

Thank you for being patient as well as civil in your post.  Most on here are not doing that.

**Comment by lowjames** [comment] 2016-06-29 18:40
While downloading the app. It said app not installed

**Comment by lowjames** [comment] 2016-06-29 18:40
And I opened mcpe , it was still set to .15.1

**Comment by lowjames** [comment] 2016-06-29 18:43
Is thare any official release date for Blocklauncher?
