### ISSUE TITLE
Level.spawnMob() bug on EntityType.LIGHTNING_BOLT

### ISSUE THREAD

**Issue by KairusDarkSeeker** [zhuowei/MCPELauncher#671] opened 2016-02-26 10:09 UTC
Level.spawnMob() on the lightning bolt entity doesn't spawn @zhuowei pls fix

**Comment by zhuowei** [comment] 2016-02-27 01:34
Duplicate of #479.

**Comment by zhuowei** [comment] 2016-02-27 04:16
It was a dumb mistake: fixed.

**Closed by zhuowei** 2016-02-27 04:16 UTC
