### ISSUE TITLE
No issues here just a question

### ISSUE THREAD

**Issue by ck1988** [zhuowei/MCPELauncher#1422] opened 2016-10-13 17:12 UTC
@zedman2000 I was wondering if you know of any mod creator's that keep up to date with their mods because I am looking to get some help with a project as that I am not a mod creator I have a few ideas for a mod pack that I am trying to get created for a YouTube series in the future once blocklauncher is updated for the mcpe 0.16.0 official updated and I will most likely ask you and your friends that play mcpe to come and join me on the journey of a pretty epic modded game play. So I send you this invite in hopes for your help with a huge mod pack

**Comment by zedman2000** [comment] 2016-10-13 20:57
Firstly, please close this so Zhouwei doesn't have to.

Second, thanks for the invite.  I probably will not have time to play.  I have been busy with my family as well as learning to weld.  I would be happy to help you as I can with your "huge modpack".  For the most part, the issue is when modders overlap used items.

Third, @ck1988 I think all mod creators are keeping up with their mods.  I think the only reason there is a DIP in MOD creation/updates now is due to ADDON support as well as the uncertainty of what will happen with 0.16.  Most minor mods can be included using just an ADDON.

Personally, all my mods that I have tested seemed to work as of 0.15.6.  I've not updated anything specifically for 0.15.9.  I know that a few of my mods will need to be updated.  In fact, I'm not even sure if anyone can download my mods.  Google Drive changed some features and I had to move everything to MediaFire, however I never finished that process yet.  I also have 5 mods in the works.  3 Epic Level, 3 normal, 3 small.  1 Normal and 2 small are done (one released), however I need to document and make the instructions / documentation before I release the others.  As that needs to be done, I've just been waiting for 0.16 before I push these out.  In total, I have 6 in various stages of completion.

The 3 EPIC ones, I have 1 about 80% coded but needs a multi-threaded game engine.  I've finished the planning for the engine, but it needs code.  The other one is conceptual but fully planned and already has buy-in from various MCPE celebrities.  The last one is 90% coded, but the HUD (human interface) is giving me trouble.  I worked with a producer/director to ensure that the story behind it is really EPIC!  As for the HUD, I provided what I have to a few other modders and everyone agrees that I am terrible at that kind of thing!  I agree!  However, a wise man once told me "Better is the enemy of good enough" and I think when I have some time, I'll be forging forward with that EPIC mod next.  Although, looking at my notes, it seems that one has an issue whereupon the MCPE game engine is not able to provide enough block information to one of my detection algorithms fast enough.  I'll have to re-write that algorithm to account for that.  Probably just eliminate the feature that is provided by that algorithm.

Of the normal mods, as I said, one is done and just needs documentation.  The other two have enough code to prove that the MCPE game engine can handle what I need it to do.  If I setup an area in a creative world to tickle the code, everything seems to work as intended.  That means I should be able to take that code and wrap in all the logic needed to ensure that someone can't bugger up their game.  Unfortunately, that is the code that takes the longest to write.  Figure if I had time to work on it, ~2 months of weekend nights of code and testing.  Not a lot of time, but time that I've been spending on welding up Go Karts.

The little mods, I released one and then I got busy with life.  The others are sitting there waiting.  One is written, three are conceptual and as I said, one was released. 

There's also some stuff I want to do to cleanup my older mods - reorganize features/etc. so that they can play nicer together feature-wise.  Such as the Super Door Operator.  It has the ability to plant things...that should be separated as some people do not need that, or since we have pistons now, some people do not want to have the door feature.  Plus there is redstone that I need to add into it.  All the little things need to get worked out and what-not.

Anyway, feel free to contact me on Twitter to continue this.

**Comment by ck1988** [comment] 2016-10-13 21:28
@zedman2000 ok I will be closing this hit me up on Facebook Howard Ramey it should be a pic of me and I can give you the details on the mod pack that I am looking to create.

**Closed** 2016-10-13 21:29 UTC

**Comment by zedman2000** [comment] 2016-10-14 14:33
@ck1988 I'm not on Facebook.  I do use Twitter, but only marginally.

**Comment by ck1988** [comment] 2016-10-16 14:00
@zedman2000 can't find you 
Here is my name on Twitter
@RameyHoward
