### ISSUE TITLE
When I open the blocklauncher it crashes

### ISSUE THREAD

**Issue by Affectingapple** [zhuowei/MCPELauncher#1199] opened 2016-06-29 08:50 UTC
Hi, when i open the blocklauncher it instantly crash
My phone is:
Asus Zenfone 2 Laser ZE500KL

**Comment by Minecraft101101** [comment] 2016-06-29 10:20
Can you guys please update the app, I thought it was supposed to be updated by the end of last week

**Comment by zedman2000** [comment] 2016-06-29 13:20
If you have updated Minecraft to 0.15, that is why.  BlockLauncher does not support 0.15 yet.  Please close this so we do not have to sort this later.  The issue is being worked on.
Check twitter and you'll see that he is having issues with OpenGL and closing the app as well as a few more things.  What should have been a week has gotten much longer.

**Closed** 2016-06-30 07:54 UTC
