### ISSUE TITLE
Chat Button disappeared

### ISSUE THREAD

**Issue by Godsoft029** [zhuowei/MCPELauncher#679] opened 2016-02-27 21:51 UTC
The chat Button just disappeared in Multiplayer and I dont know why.
This never happened for me before and its latest beta.
Pic:http://imgur.com/tVn8xvU

**Comment by zhuowei** [comment] 2016-02-28 00:17
@Godsoft029 Which server is this? I can't find any servers that are creative when you log in...

**Comment by zhuowei** [comment] 2016-02-28 00:25
@Godsoft029 I can't reproduce this: on latest beta, connecting to b58719.leet.cc:58719, the chat button doesn't disappear (either in regular or desktop UI). Which device is this, and which mods are you using?

**Comment by Godsoft029** [comment] 2016-02-28 08:28
Im currently using Alpha Hack and Servicehack and I cannot reproduce too. This happened to me once. Im using the Sony Xperia Z1 compact(Android 5.1.1)

**Comment by zhuowei** [comment] 2016-03-02 17:13
I'm not sure what happened there. Closing.

**Closed by zhuowei** 2016-03-02 17:13 UTC
Labels: bug
