### ISSUE TITLE
The Minecraft PE15.1 update came out,IT NEEDS TO WORK FOR THAT TOO!!!

### ISSUE THREAD

**Issue by lowjames** [zhuowei/MCPELauncher#1179] opened 2016-06-27 19:03 UTC
Make it work with the MCPE 15.1 Update!

**Comment by staticshock8345** [comment] 2016-06-27 19:42
Is it working now withnowpe 15.1 bc its not working for me

**Comment by staticshock8345** [comment] 2016-06-27 19:43
Mcpe i mean

**Comment by lowjames** [comment] 2016-06-27 20:09
No, but we need to make it work!

**Comment by staticshock8345** [comment] 2016-06-27 20:21
Ya ppl are deleting the app saying it doesint work alot of my freinds are
giving up on it

**Comment by lowjames** [comment] 2016-06-27 20:27
Well don't tell them when its fixed, that help teach them that they need to wait instead of just deleteing the app! If they ask just say you don't know.

**Comment by bringito** [comment] 2016-06-27 20:49
How long do you guys think it'll take

**Comment by lowjames** [comment] 2016-06-27 20:54
I'm not a modder, I'm just the messenger

**Comment by lowjames** [comment] 2016-06-27 20:55
Sorry, but we still don't know.

**Comment by staticshock8345** [comment] 2016-06-29 00:11
Thanks

**Comment by lowjames** [comment] 2016-06-29 00:48
np!

**Comment by zedman2000** [comment] 2016-06-29 13:29
@lowjames Please close this so we do not have to sort this later.  The issue is being worked on.
Check twitter and you'll see that he is having issues with OpenGL and closing the app as well as a few more things.  What should have been a week has gotten much longer.  Please close this issue so the author does not have to sort this out later.

**Closed** 2016-06-29 18:48 UTC
