### ISSUE TITLE
BUG? function startDestroyBlock(x,y,z,side){} is not working.

### ISSUE THREAD

**Issue by Yroki12** [zhuowei/MCPELauncher#368] opened 2015-12-02 15:29 UTC
//code
function startDestroyBlock(x,y,z,side){
var lg=Level.getTile(x,y,z);
var c=0; c++
if(lg==1){
Entity.setHealth(getPlayerEnt(),0);
                }  }
I wrote it, but it wasn't work. But no error.
Is it a bug?

**Comment by Khristian-kun** [comment] 2015-12-02 19:20
thats because it only works when you start, not while destroying block, maybe @zhuowei has do add a hook called function whileDestroyBlock(x,y,z,side,progress);

**Comment by zhuowei** [comment] 2015-12-02 20:57
Sorry about that! this is a known issue: duplicate of #326.

**Closed by zhuowei** 2015-12-02 20:57 UTC

**Comment by Yroki12** [comment] 2015-12-03 01:30
I see. Thx both:)

**Comment by Yroki12** [comment] 2015-12-03 09:03
@Khristian-kun 
I can't use that code
