### ISSUE TITLE
⠀

### ISSUE THREAD

**Issue by nimanajmi** [zhuowei/MCPELauncher#1162] opened 2016-06-25 08:04 UTC

**Comment by pawsthehelper** [comment] 2016-06-27 01:40
If your Minecraft is updated to .15 then they will be fixing this issue by the end of today hope this helps

**Comment by zedman2000** [comment] 2016-06-29 13:32
I can offer that if you have updated Minecraft to 0.15, that is why.  BlockLauncher does not support 0.15 yet.  Please close this so we do not have to sort this later.  The issue is being worked on.
Check twitter and you'll see that he is having issues with OpenGL and closing the app as well as a few more things.  What should have been a week has gotten much longer.  Please close this issue so the author does not have to sort this out later.

**Closed** 2021-09-20 23:11 UTC
